/*1327708588,169775556*/

if (window.CavalryLogger) { CavalryLogger.start_js(["6kHia"]); }

function HackerCupAlertsController(a,b){copy_properties(this,{elem:$(a),round_id:b,timer_id:null});this.start();}copy_properties(HackerCupAlertsController.prototype,{start:function(){if(this.timer_id===null)this._runAlerts();return false;},_runAlerts:function(){var a=new AsyncRequest().setURI('/hackercup/ajax/alerts.php').setData({round_id:this.round_id}).send();this.timer_id=setTimeout(this._runAlerts.bind(this),60000);return false;}});
function HackerCupConst(){}copy_properties(HackerCupConst,{START_TIMER:'hackercup_start_timer',SUCCESSFUL_UPLOAD:'successful_upload'});
function HackerCupLastSubmitController(b,c){copy_properties(this,{elem:$(b),problem_id:c});var a=this.update.bind(this);var d=HackerCupConst.SUCCESSFUL_UPLOAD;Arbiter.subscribe(d,a);this.update();}copy_properties(HackerCupLastSubmitController.prototype,{update:function(){var a=new AsyncRequest().setURI('/hackercup/ajax/last_submission.php').setData({problem_id:this.problem_id}).send();}});
function HackerCupTimerController(b,g,f,e,c,d){copy_properties(this,{elem:$(b),time_remaining:g,refid:e,expired:c,label:d});this.started=false;var a=this._onInform.bind(this);var h=HackerCupConst.START_TIMER;Arbiter.subscribe(h,a);if(f)this.start();}copy_properties(HackerCupTimerController.prototype,{displayDiv:null,elem:null,end_time:null,expired:null,label:null,labelDiv:null,refid:null,running:null,started:null,time_remaining:null,start:function(){if(this.started)return false;this.started=true;this.end_time=new Date().getTime()+this.time_remaining*1000;this.displayDiv=DOM.find(this.elem,'div.HackerCupTimer_display');if(!this.running){if(this.label){this.labelDiv=DOM.find(this.elem,'div.HackerCupTimer_label');DOM.setContent(this.labelDiv,this.label);}this._runTimer();}this.running=true;return false;},_onInform:function(b,a){if(a.problem_id==this.refid)this.start();},_runTimer:function(){if(!this.started)return false;var c,d;var a=new Date().getTime();var f=Math.round((this.end_time-a)/1000);if(f>=0){var g=f;var e=g%60;g=parseInt(g/60,10);var b=g%60;g=parseInt(g/60,10);if(e<10)e='0'+e;if(b<10)b='0'+b;d=[];if(g)d.push(g);d.push(b);d.push(e);c=d.join(':');}else c=this.expired;DOM.setContent(this.displayDiv,c);setTimeout(this._runTimer.bind(this),1000);return false;}});
function downloadInput(a,b){document.forms['get_'+a].submit();Arbiter.inform(HackerCupConst.START_TIMER,{problem_id:a});}
window.HackerCup={complete:function(a){DOM.setContent($('hackercup_submit_controls'),a);CSS.removeClass('hackercup_submit','async_saving');Arbiter.inform(HackerCupConst.SUCCESSFUL_UPLOAD,{});},incomplete:function(a){DOM.setContent($('hackercup_submit_message'),a);CSS.removeClass('hackercup_submit','async_saving');}};
function UIDataTableController(){}UIDataTableController.prototype={selectedRow:null,selectionEnabled:true,init:function(a){this.args=a;this.selectedRow=this.args.selectedRow;},sortColumn:function(b,a,c){if(this.args.header){CSS.removeClass(this.args.header,'sortedDesc');CSS.removeClass(this.args.header,'sortedAsc');}this.args.order=this.args.column==a?!this.args.order:c;this.args.column=a;this.args.header=b;CSS.addClass(b,this.args.order?'sortedDesc':'sortedAsc');this.args.rows.sort(this._sort.bind(this));body=DOM.scry(this.args.table,'tbody')[0];for(i=0;i<this.args.rows.length;i++){row_element=$(this.args.rows[i].element);CSS.conditionClass(row_element,'odd',i%2==1);CSS.conditionClass(row_element,'hidden',i>=this.args.max_visible);DOM.appendContent(body,row_element);}},_sort:function(a,b){valueA=a.sort_values[this.args.column];valueB=b.sort_values[this.args.column];var c=(valueB<valueA)-(valueA<valueB);return (this.args.order?-1:1)*c;},selectRow:function(b,a){if(!this.selectionEnabled)return false;this.deselectRow();this.selectedRow=b;CSS.addClass(b,'selectedRow');for(var c in a)Arbiter.inform(c,a[c]);return true;},deselectRow:function(){if(this.selectedRow)CSS.removeClass(this.selectedRow,'selectedRow');},disableSelection:function(){this.selectionEnabled=false;},enableSelection:function(){this.selectionEnabled=true;}};